### ISSUE TITLE
freeze with carmine with lz4-compressor

### ISSUE THREAD

**Issue by ilevd** [ptaoussanis/nippy#148] opened 2022-04-11 16:33 UTC
Try to write to Redis with lz4-compressor, found this way:

```clj
(defn write-cache [key val]
  (car/wcar redis (car/set key (WrappedForFreezing. val {:compressor taoensso.nippy/lz4-compressor}))))
```
it would be better to set compressor with `*freeze-opts*`:
```clj
(defn write-cache [key val]
  (binding [taoensso.nippy.tools/*freeze-opts* {:compressor taoensso.nippy/lz4-compressor}]
    (car/wcar redis (car/set key val))))
```
but it doesn't work, cause there is no merge with `*freeze-opts*` if the value isn't `WrappedForFreezing` in https://github.com/ptaoussanis/nippy/blob/master/src/taoensso/nippy/tools.clj#L36

Shouldn't merge with `*freeze-opts*` be there too?
Btw, is there completely another way to set compressor properly (maybe in carmime)?

**Comment by ptaoussanis** [comment] 2022-06-23 11:06
@ilevd Hi Igor, thanks for the report! This is indeed a bug (unintended behaviour), will be fixed in next release later today.

**Closed by ptaoussanis** 2022-06-23 11:06 UTC
Labels: bug
